spring:
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/michelet_db?currentSchema=timeslot_service

eureka:
  instance:
    hostname: timeslot-service
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/