server:
  port: 19400

spring:
  application:
    name: timeslot-service

  datasource:
    url: jdbc:postgresql://localhost:19410/timeslot_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

internal:
  auth:
    secret: ${SPRING_INTERNAL_AUTH_SECRET}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false