server:
  port: ${SERVER_PORT:19400}
  tomcat:
    threads:
      max: 300
      min-spare: 20
    accept-count: 200

spring:
  application:
    name: timeslot-service
  
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}