### 환경 변수 설정
@gatewayUrl = http://localhost:19000
@timeSlotServiceUrl = http://localhost:19400
@restaurantId = d4246628-b7da-47ab-95bb-a126395f0628
@timeSlotId = b184211a-bd71-478e-8f14-ce889ba9db1d
@ownerToken = {{ownerToken}}
@userToken = {{userToken}}
@X-User-Id = 550e8400-e29b-41d4-a716-446655440000
@X-User-Role = OWNER
@X-Internal-Token = {{X-Internal-Token}}


### 1. [외부 API] 특정 날짜의 타임슬롯 목록 조회
GET {{gatewayUrl}}/api/v1/restaurants/{{restaurantId}}/time-slots?targetDate=2026-05-31
Accept: application/json
Authorization: Bearer {{userToken}}

### 2. [외부 API] 타임슬롯 일괄 생성 (관리자 전용)
POST {{gatewayUrl}}/api/v1/restaurants/{{restaurantId}}/time-slots/bulk
Content-Type: application/json
Authorization: Bearer {{ownerToken}}

{
  "startDate": "2026-05-05",
  "endDate": "2026-05-10",
  "openTime": "10:00:00",
  "closeTime": "22:00:00",
  "intervalMinutes": 60,
  "capacity": 4
}


### 3. [외부 API] 월간 달력(예약 가능 여부) 조회
GET {{gatewayUrl}}/api/v1/restaurants/{{restaurantId}}/time-slots/calendar?year=2026&month=5
Authorization: Bearer {{userToken}}
Accept: application/json


### 4. [내부 API] deductTimeSlotCapacity - 예약 시 타임슬롯의 남은 좌석 수 감소
POST {{timeSlotServiceUrl}}/internal/v1/timeslots/{{timeSlotId}}/deduct
Content-Type: application/json
X-User-Id: {{X-User-Id}}
X-User-Role: {{X-User-Role}}
X-Internal-Token: {{X-Internal-Token}}

{
  "deductCapacity": 1
}